variable "vpc_name" {}
variable "vpc_cidr" {}
variable "azs" {}
variable "public_subnet_cidrs" {}
variable "private_subnet_cidrs" {}
variable "region" {}
variable "ami" {}
variable "instance_type" {}
variable "key_name" {}
variable "env" {}
variable "dynamo_db" {}
variable "s3_bucket" {}
variable "test_role_arn" {}
variable "qa_role_arn" {}
