variable "vpc_name" {}
variable "vpc_cidr" {}
variable "subnet_cidr1" {}
variable "subnet_cidr2" {}
variable "ami" {}
variable "instance_type" {}
variable "key_name" {}
variable "env" {}
variable "region" {}
